config/routes.rb
Rails.application.routes.draw do
  resources :cat_ownerships
  resources :comments
  resources :cats
  devise_for :users

  # Set the landing page as root
  root "static#landing"
  get "/landing" => "static#landing", as: :landing
  get "/success" => "static#payment_accepted", as: :success
  get "/my_cats" => "static#my_cats", as: :my_cats
  get "/easter_egg" => "static#easter_egg", as: :easter_egg
  get "/cart" => "static#cart", as: :cart
  get "/about" => "static#about", as: :about
  post 'static/add', to: 'static#add_to_cart', as: :add_to_cart
  post 'static/remove', to: 'static#remove_from_cart', as: :remove_from_cart
  post 'checkout', to: 'checkout#create'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/cat_ownership.rb
class CatOwnership < ApplicationRecord
    belongs_to :user
    belongs_to :cat
end

app/controllers/cat_ownerships_controller.rb
class CatOwnershipsController < ApplicationController
  before_action :set_cat_ownership, only: %i[ show edit update destroy ]

  # GET /cat_ownerships or /cat_ownerships.json
  def index
    @cat_ownerships = CatOwnership.all
  end

  # GET /cat_ownerships/1 or /cat_ownerships/1.json
  def show
  end

  # GET /cat_ownerships/new
  def new
    @cat_ownership = CatOwnership.new
  end

  # GET /cat_ownerships/1/edit
  def edit
  end

  # POST /cat_ownerships or /cat_ownerships.json
  def create
    @cat_ownership = CatOwnership.new(cat_ownership_params)

    respond_to do |format|
      if @cat_ownership.save
        format.html { redirect_to @cat_ownership, notice: "Cat ownership was successfully created." }
        format.json { render :show, status: :created, location: @cat_ownership }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cat_ownership.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cat_ownerships/1 or /cat_ownerships/1.json
  def update
    respond_to do |format|
      if @cat_ownership.update(cat_ownership_params)
        format.html { redirect_to @cat_ownership, notice: "Cat ownership was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @cat_ownership }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cat_ownership.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cat_ownerships/1 or /cat_ownerships/1.json
  def destroy
    @cat_ownership.destroy!

    respond_to do |format|
      format.html { redirect_to cat_ownerships_path, notice: "Cat ownership was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cat_ownership
      @cat_ownership = CatOwnership.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def cat_ownership_params
      params.fetch(:cat_ownership, {})
    end
end

app/helpers/cat_ownerships_helper.rb
module CatOwnershipsHelper
end

app/views/cat_ownerships/_cat_ownership.html.erb
<div id="<%= dom_id cat_ownership %>">
</div>

app/views/cat_ownerships/_form.html.erb
<%= form_with(model: cat_ownership) do |form| %>
  <% if cat_ownership.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(cat_ownership.errors.count, "error") %> prohibited this cat_ownership from being saved:</h2>

      <ul>
        <% cat_ownership.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/cat_ownerships/edit.html.erb
<% content_for :title, "Editing cat ownership" %>

<h1>Editing cat ownership</h1>

<%= render "form", cat_ownership: @cat_ownership %>

<br>

<div>
  <%= link_to "Show this cat ownership", @cat_ownership %> |
  <%= link_to "Back to cat ownerships", cat_ownerships_path %>
</div>

app/views/cat_ownerships/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Cat ownerships" %>

<h1>Cat ownerships</h1>

<div id="cat_ownerships">
  <% @cat_ownerships.each do |cat_ownership| %>
    <%= render cat_ownership %>
    <p>
      <%= link_to "Show this cat ownership", cat_ownership %>
    </p>
  <% end %>
</div>

<%= link_to "New cat ownership", new_cat_ownership_path %>

app/views/cat_ownerships/new.html.erb
<% content_for :title, "New cat ownership" %>

<h1>New cat ownership</h1>

<%= render "form", cat_ownership: @cat_ownership %>

<br>

<div>
  <%= link_to "Back to cat ownerships", cat_ownerships_path %>
</div>

app/views/cat_ownerships/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @cat_ownership %>

<div>
  <%= link_to "Edit this cat ownership", edit_cat_ownership_path(@cat_ownership) %> |
  <%= link_to "Back to cat ownerships", cat_ownerships_path %>

  <%= button_to "Destroy this cat ownership", @cat_ownership, method: :delete %>
  
</div>