config/routes.rb
Rails.application.routes.draw do
  resources :cat_ownerships
  resources :comments
  resources :cats
  devise_for :users

  # Set the landing page as root
  root "static#landing"
  get "/landing" => "static#landing", as: :landing
  get "/success" => "static#payment_accepted", as: :success
  get "/my_cats" => "static#my_cats", as: :my_cats
  get "/easter_egg" => "static#easter_egg", as: :easter_egg
  get "/cart" => "static#cart", as: :cart
  get "/about" => "static#about", as: :about
  post 'static/add', to: 'static#add_to_cart', as: :add_to_cart
  post 'static/remove', to: 'static#remove_from_cart', as: :remove_from_cart
  post 'checkout', to: 'checkout#create'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <a class="navbar-brand center mx-auto fs-1" href="<%=root_path%>">Super Cat</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="<%=cats_path%>">Find cats</a>
                </li>
                <%if current_user%>
                    <li class="nav-item">
                        <a class="nav-link active" href="<%=my_cats_path%>">My cats</a>
                    </li>
                    <li class="nav-item">
                        <%= link_to "Log out", destroy_user_session_path, data: { turbo_method: :delete }, class: "nav-link active" %>
                    </li>
                <%else%>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="<%=new_user_session_path%>">
                            Login
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="<%=new_user_registration_path%>">
                            Register
                        </a>
                    </li>
                    <%end%>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="<%=cart_path%>">
                        Cat Basket
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Super Cat" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js" integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>


</html>